### ISSUE TITLE
TypeError: Cannot read property 'setDefaultExtra' of undefined

### ISSUE THREAD

**Issue by ElegantLin** [theprimone/ant-design-pro-v2-plus#3]
Module../src/global.js
src/global.js:7
 >  4 | import { FormMateConfig } from 'antd-curd';
   5 | import defaultSettings from './defaultSettings';
   6 | 
  **7 | const { setDefaultExtra } = FormMateConfig;**
   8 | setDefaultExtra({
   9 |   picture: '自定义图片默认提示',
  10 | });

I met this error in line 7. I am fresh in frontend. Could you please help me with this?

Thanks a lot.

**Comment by theprimone** [comment]
So, why not show me the exact error message?

**Comment by theprimone** [comment]
It's my fault, **antd-curd** had renamed `FormMateConfig` to `formMateConfig`. But the verison number is still 0.2.*(0.2.6 -> 0.2.9). So it's not compatible with 0.2.9 you installed.

It's fixed now. And you just rename `FormMateConfig` to `formMateConfig`, this will be work now.

**Comment by ElegantLin** [comment]
This problem is solved.

Thanks a lot.
