### ISSUE TITLE
Search cannot be used in the curd page

### ISSUE THREAD

**Issue by ElegantLin** [theprimone/ant-design-pro-v2-plus#4]
Hello, 

The search function on the curd page cannot be used. I am not sure it is my error while using or not. Could you please check it ?

Thanks a lot.

**Comment by theprimone** [comment]
Is [CurdPage](https://github.com/theprimone/ant-design-pro-v2-plus/tree/master/src/pages/Enhance/CurdPage) work?

In addition, paste the usage of your code is better.

**Comment by ElegantLin** [comment]
You can try this on your [demo page](https://theprimone.top/ant-design-pro-v2-plus/enhance/curd-page).  If you type a name in the input element and click search. But you can still find the other records.

**Comment by theprimone** [comment]
You can see the search params in Network tab of BROWSER if `process.env.ENV === 'development'`. And this is service of CurdPage: [services/curdPage.ts](https://github.com/theprimone/ant-design-pro-v2-plus/blob/master/src/services/curdPage.ts).

Moreover, I don't precess the search params [mock data with umi](https://umijs.org/zh/guide/mock-data.html) :flushed: And it's **only USABLE** in development environment. So I write mock data in [HERE](https://github.com/theprimone/ant-design-pro-v2-plus/blob/master/src/services/mock/curdPage.js) to use after `process.env.ENV === 'production'`.

In a word, it's **OK**, you can clone and start the repo to test.

**Comment by ElegantLin** [comment]
Well, thanks for your reply. I will try it.
